export const USER_LOAD = 'USER_LOAD';
export const USER_LOAD_SUCCESS = 'USER_LOAD_SUCCESS';
export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';
export const USER_LOGOUT_FAIL = 'USER_LOGOUT_FAIL';
export const USER_SIGNUP = 'USER_SIGNUP';
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
export const USER_SIGNUP_FAIL = 'USER_SIGNUP_FAIL';

export const SPEC_INIT = 'SPEC_INIT';
export const SPEC_UPDATE = 'SPEC_UPDATE';
export const SPEC_UPDATE_SUCCESS = 'SPEC_UPDATE_SUCCESS';
export const SPEC_UPDATE_FAIL = 'SPEC_UPDATE_FAIL';
export const SPEC_LOAD_INFO = 'SPEC_LOAD_INFO';
export const SPEC_LOAD_INFO_SUCCESS = 'SPEC_LOAD_INFO_SUCCESS';
export const SPEC_LOAD_INFO_FAIL = 'SPEC_LOAD_INFO_FAIL';
export const SPEC_LOAD = 'SPEC_LOAD';
export const SPEC_LOAD_SUCCESS = 'SPEC_LOAD_SUCCESS';
export const SPEC_LOAD_FAIL = 'SPEC_LOAD_FAIL';

export const TOOLS_LOAD = 'TOOLS_LOAD';
export const TOOLS_LOAD_SUCCESS = 'TOOLS_LOAD_SUCCESS';
export const TOOLS_LOAD_FAIL = 'TOOLS_LOAD_FAIL';
